repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    name: check for added large files
    description: prevents giant files from being committed.
    entry: check-added-large-files
    language: python
    hooks: 
    - id: check-added-large-files
 
